// android/build.gradle

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // You can add classpath dependencies here if needed
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
