// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIb_HXAf5ix5ApminTMRwPwUnueDuGLrk',
    appId: '1:710538185326:web:9380e9acc16e7631e0f47f',
    messagingSenderId: '710538185326',
    projectId: 'fluxcode-47db9',
    authDomain: 'fluxcode-47db9.firebaseapp.com',
    storageBucket: 'fluxcode-47db9.firebasestorage.app',
    measurementId: 'G-T1MJLC11BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkpaW-49GR6jACDdv6-fIMwOiKYV7F-Ek',
    appId: '1:710538185326:android:af5d3abdadfd7531e0f47f',
    messagingSenderId: '710538185326',
    projectId: 'fluxcode-47db9',
    storageBucket: 'fluxcode-47db9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwT7Cb_IpuMbrog_4K7uSRqaLPjfPcUlg',
    appId: '1:710538185326:ios:8d21f06aca7b8235e0f47f',
    messagingSenderId: '710538185326',
    projectId: 'fluxcode-47db9',
    storageBucket: 'fluxcode-47db9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwT7Cb_IpuMbrog_4K7uSRqaLPjfPcUlg',
    appId: '1:710538185326:ios:8d21f06aca7b8235e0f47f',
    messagingSenderId: '710538185326',
    projectId: 'fluxcode-47db9',
    storageBucket: 'fluxcode-47db9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIb_HXAf5ix5ApminTMRwPwUnueDuGLrk',
    appId: '1:710538185326:web:c73e97df2057172ee0f47f',
    messagingSenderId: '710538185326',
    projectId: 'fluxcode-47db9',
    authDomain: 'fluxcode-47db9.firebaseapp.com',
    storageBucket: 'fluxcode-47db9.firebasestorage.app',
    measurementId: 'G-ZCJ8ZPZ3PE',
  );
}
